import { Employee } from "./types";

export const employees: Employee[] = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 28,
    salary: 72000,
    createdAt: new Date("2022-01-15"),
    status: "verified",
    role: "Developer",
    skills: ["React", "TypeScript", "Node.js"],
    department: "Engineering",
    manager: "John Smith",
    phone: "+1-555-1001",
    address: { city: "New York", country: "USA" },
    projects: ["CRM", "Dashboard"],
  },
  {
    id: 2,
    name: "Bob Williams",
    email: "bob.williams@example.com",
    age: 35,
    salary: 85000,
    createdAt: new Date("2021-03-20"),
    status: "verified",
    role: "Manager",
    skills: ["AWS", "Docker"],
    department: "Engineering",
    manager: null,
    phone: "+1-555-1002",
    address: { city: "Chicago", country: "USA" },
    projects: ["Infrastructure"],
  },
  {
    id: 3,
    name: "Charlie Brown",
    email: "charlie.brown@example.com",
    age: 24,
    salary: 61000,
    createdAt: new Date("2023-06-01"),
    status: "active",
    role: "QA",
    skills: ["TypeScript", "React"],
    department: "QA",
    manager: "Bob Williams",
    address: { city: "Austin", country: "USA" },
    projects: ["Automation"],
  },
  {
    id: 4,
    name: "Diana Miller",
    email: "diana.miller@example.com",
    age: 31,
    salary: 69000,
    createdAt: new Date("2020-10-11"),
    status: "nonactive",
    role: "Designer",
    skills: ["Vue", "GraphQL"],
    department: "Design",
    manager: "Emma Davis",
    phone: "+1-555-1004",
    address: { city: "Seattle", country: "USA" },
    projects: ["Design System"],
  },
  {
    id: 5,
    name: "Ethan Davis",
    email: "ethan.davis@example.com",
    age: 29,
    salary: 76000,
    createdAt: new Date("2022-05-09"),
    status: "verified",
    role: "Developer",
    skills: ["Node.js", "Docker", "AWS"],
    department: "Engineering",
    manager: "Bob Williams",
    address: { city: "Boston", country: "USA" },
    projects: ["API Gateway"],
  },
  {
    id: 6,
    name: "Fiona Clark",
    email: "fiona.clark@example.com",
    age: 26,
    salary: 64000,
    createdAt: new Date("2024-01-18"),
    status: "active",
    role: "Support",
    skills: ["React"],
    department: "Customer Success",
    manager: "Grace Hall",
    phone: "+1-555-1006",
    address: { city: "Denver", country: "USA" },
    projects: ["Help Center"],
  },
  {
    id: 7,
    name: "George Hall",
    email: "george.hall@example.com",
    age: 41,
    salary: 98000,
    createdAt: new Date("2018-04-15"),
    status: "verified",
    role: "Admin",
    skills: ["AWS", "Docker", "Go"],
    department: "IT",
    manager: null,
    address: { city: "San Francisco", country: "USA" },
    projects: ["Cloud Migration"],
  },
  {
    id: 8,
    name: "Hannah Lewis",
    email: "hannah.lewis@example.com",
    age: 27,
    salary: 68000,
    createdAt: new Date("2021-11-01"),
    status: "banned",
    role: "Developer",
    skills: ["Angular", "TypeScript"],
    department: "Engineering",
    manager: "Bob Williams",
    phone: "+1-555-1008",
    address: { city: "Miami", country: "USA" },
    projects: ["Portal"],
  },
  {
    id: 9,
    name: "Ian Walker",
    email: "ian.walker@example.com",
    age: 33,
    salary: 82000,
    createdAt: new Date("2019-07-22"),
    status: "verified",
    role: "Developer",
    skills: ["Go", "Docker", "AWS"],
    department: "Platform",
    manager: "George Hall",
    address: { city: "Dallas", country: "USA" },
    projects: ["Kubernetes"],
  },
  {
    id: 10,
    name: "Julia Young",
    email: "julia.young@example.com",
    age: 30,
    salary: 71000,
    createdAt: new Date("2022-09-12"),
    status: "verified",
    role: "Designer",
    skills: ["React", "GraphQL"],
    department: "Design",
    manager: "Emma Davis",
    address: { city: "Portland", country: "USA" },
    projects: ["Website"],
  },
  {
    id: 11,
    name: "Kevin Harris",
    email: "kevin.harris@example.com",
    age: 38,
    salary: 92000,
    createdAt: new Date("2017-05-14"),
    status: "verified",
    role: "Manager",
    skills: ["AWS", "Node.js"],
    department: "Operations",
    manager: null,
    address: { city: "Atlanta", country: "USA" },
    projects: ["ERP"],
  },
  {
    id: 12,
    name: "Laura Scott",
    email: "laura.scott@example.com",
    age: 25,
    salary: 60000,
    createdAt: new Date("2024-02-10"),
    status: "active",
    role: "QA",
    skills: ["React", "TypeScript"],
    department: "QA",
    manager: "Kevin Harris",
    address: { city: "Phoenix", country: "USA" },
    projects: ["Regression"],
  },
  {
    id: 13,
    name: "Michael Green",
    email: "michael.green@example.com",
    age: 37,
    salary: 89000,
    createdAt: new Date("2019-09-18"),
    status: "verified",
    role: "Developer",
    skills: ["Python", "AWS"],
    department: "AI",
    manager: "Bob Williams",
    address: { city: "San Jose", country: "USA" },
    projects: ["ML Platform"],
  },
  {
    id: 14,
    name: "Nina Adams",
    email: "nina.adams@example.com",
    age: 29,
    salary: 73000,
    createdAt: new Date("2020-12-08"),
    status: "nonactive",
    role: "Support",
    skills: ["Vue"],
    department: "Support",
    manager: "Grace Hall",
    address: { city: "Las Vegas", country: "USA" },
    projects: ["Knowledge Base"],
  },
  {
    id: 15,
    name: "Oliver Baker",
    email: "oliver.baker@example.com",
    age: 34,
    salary: 81000,
    createdAt: new Date("2021-08-19"),
    status: "verified",
    role: "Developer",
    skills: ["Node.js", "GraphQL"],
    department: "Engineering",
    manager: "Bob Williams",
    address: { city: "Houston", country: "USA" },
    projects: ["Payments"],
  },
  {
    id: 16,
    name: "Paula Carter",
    email: "paula.carter@example.com",
    age: 28,
    salary: 67000,
    createdAt: new Date("2023-01-30"),
    status: "verified",
    role: "Designer",
    skills: ["Vue", "React"],
    department: "Design",
    manager: "Emma Davis",
    address: { city: "Orlando", country: "USA" },
    projects: ["Branding"],
  },
  {
    id: 17,
    name: "Quinn Evans",
    email: "quinn.evans@example.com",
    age: 32,
    salary: 78000,
    createdAt: new Date("2022-06-14"),
    status: "verified",
    role: "Developer",
    skills: ["Go", "Docker"],
    department: "Platform",
    manager: "George Hall",
    address: { city: "Charlotte", country: "USA" },
    projects: ["Service Mesh"],
  },
  {
    id: 18,
    name: "Rachel Flores",
    email: "rachel.flores@example.com",
    age: 27,
    salary: 65000,
    createdAt: new Date("2023-03-07"),
    status: "banned",
    role: "QA",
    skills: ["Angular"],
    department: "QA",
    manager: "Kevin Harris",
    address: { city: "Nashville", country: "USA" },
    projects: ["Testing"],
  },
  {
    id: 19,
    name: "Samuel Gray",
    email: "samuel.gray@example.com",
    age: 36,
    salary: 91000,
    createdAt: new Date("2018-02-11"),
    status: "verified",
    role: "Admin",
    skills: ["AWS", "Docker", "Python"],
    department: "IT",
    manager: null,
    address: { city: "Detroit", country: "USA" },
    projects: ["Security"],
  },
  {
    id: 20,
    name: "Tina Hill",
    email: "tina.hill@example.com",
    age: 26,
    salary: 62000,
    createdAt: new Date("2024-04-15"),
    status: "active",
    role: "Support",
    skills: ["React"],
    department: "Customer Success",
    manager: "Grace Hall",
    address: { city: "Salt Lake City", country: "USA" },
    projects: ["Live Chat"],
  },
  {
    id: 21,
    name: "Uma King",
    email: "uma.king@example.com",
    age: 31,
    salary: 74000,
    createdAt: new Date("2021-07-21"),
    status: "verified",
    role: "Developer",
    skills: ["TypeScript", "React", "GraphQL"],
    department: "Engineering",
    manager: "Bob Williams",
    address: { city: "Columbus", country: "USA" },
    projects: ["Admin Portal"],
  },
  {
    id: 22,
    name: "Victor Lopez",
    email: "victor.lopez@example.com",
    age: 39,
    salary: 96000,
    createdAt: new Date("2017-01-09"),
    status: "verified",
    role: "Manager",
    skills: ["AWS", "Docker", "Node.js"],
    department: "Platform",
    manager: null,
    address: { city: "San Diego", country: "USA" },
    projects: ["Observability"],
  },
  {
    id: 23,
    name: "Wendy Moore",
    email: "wendy.moore@example.com",
    age: 28,
    salary: 69000,
    createdAt: new Date("2020-06-18"),
    status: "nonactive",
    role: "Designer",
    skills: ["Vue", "React"],
    department: "Marketing",
    manager: "Emma Davis",
    address: { city: "Kansas City", country: "USA" },
    projects: ["Campaign"],
  },
  {
    id: 24,
    name: "Xavier Nelson",
    email: "xavier.nelson@example.com",
    age: 33,
    salary: 83000,
    createdAt: new Date("2019-11-03"),
    status: "verified",
    role: "Developer",
    skills: ["Python", "AWS", "GraphQL"],
    department: "AI",
    manager: "Bob Williams",
    address: { city: "Raleigh", country: "USA" },
    projects: ["Recommendation Engine"],
  },
  {
    id: 25,
    name: "Yara Owens",
    email: "yara.owens@example.com",
    age: 24,
    salary: 59000,
    createdAt: new Date("2024-05-20"),
    status: "active",
    role: "QA",
    skills: ["React", "TypeScript"],
    department: "QA",
    manager: "Kevin Harris",
    address: { city: "Tampa", country: "USA" },
    projects: ["Smoke Test"],
  },
  {
    id: 26,
    name: "Zach Parker",
    email: "zach.parker@example.com",
    age: 40,
    salary: 102000,
    createdAt: new Date("2016-08-25"),
    status: "verified",
    role: "Admin",
    skills: ["AWS", "Go", "Docker"],
    department: "IT",
    manager: null,
    address: { city: "Minneapolis", country: "USA" },
    projects: ["Infrastructure"],
  },
  {
    id: 27,
    name: "Amber Reed",
    email: "amber.reed@example.com",
    age: 30,
    salary: 75000,
    createdAt: new Date("2022-02-17"),
    status: "verified",
    role: "Developer",
    skills: ["Angular", "Node.js"],
    department: "Engineering",
    manager: "Bob Williams",
    address: { city: "Cleveland", country: "USA" },
    projects: ["Internal Tools"],
  },
  {
    id: 28,
    name: "Brian Stewart",
    email: "brian.stewart@example.com",
    age: 35,
    salary: 87000,
    createdAt: new Date("2019-04-04"),
    status: "banned",
    role: "Support",
    skills: ["Docker", "AWS"],
    department: "Support",
    manager: "Grace Hall",
    address: { city: "Indianapolis", country: "USA" },
    projects: ["Ticket System"],
  },
  {
    id: 29,
    name: "Chloe Turner",
    email: "chloe.turner@example.com",
    age: 27,
    salary: 70000,
    createdAt: new Date("2023-10-10"),
    status: "verified",
    role: "Designer",
    skills: ["React", "Vue"],
    department: "Design",
    manager: "Emma Davis",
    address: { city: "Sacramento", country: "USA" },
    projects: ["Mobile App"],
  },
  {
    id: 30,
    name: "Daniel White",
    email: "daniel.white@example.com",
    age: 32,
    salary: 84000,
    createdAt: new Date("2021-12-01"),
    status: "verified",
    role: "Developer",
    skills: ["TypeScript", "Node.js", "AWS"],
    department: "Engineering",
    manager: "Bob Williams",
    phone: "+1-555-1030",
    address: { city: "Philadelphia", country: "USA" },
    projects: ["Billing", "Analytics"],
  },
];
